Prueba_Banco/Models/ErrorViewModel.cs
namespace Prueba_Banco.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Prueba_Banco/Models/Ventas.cs
namespace Prueba_Banco.Models
{
    public class Ventas
    {
        public int id { get; set; }
        public string? CODGTE { get; set; }
        public string? NOMGTE { get; set; }
        public string? CODCOOR { get; set; }
        public string? NOMCOOR { get; set; }
        public string? CODVENTAS { get; set; }
        public string? NOMVEND { get; set; }
        public string? CODNIVEL { get; set; }
        public string? NOMNIVEL { get; set; }
        public float? NIT_CLIENTE { get; set; }
        public string? ITEM { get; set; }
        public string? NOM_CLIENTE { get; set; }
        public string? SEGMENTO { get; set; }
        public string? GERENCIADO { get; set; }
        public float? OFICINA_CLIENTE { get; set; }
        public float? FECHAFIL { get; set; }
        public int? PERIODOMED { get; set; }
        public int? CONDIC { get; set; }
        public int? CTACAMP { get; set; }

        public Ventas()
        {

        }
    }


}

Prueba_Banco/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prueba_Banco.Models;
using System.Diagnostics;

namespace Prueba_Banco.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Prueba_Banco/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Prueba_Banco.Data;
using Prueba_Banco.Models;

namespace Prueba_Banco.Controllers
{
    public class VentasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VentasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index()
        {
              return View(await _context.Ventas.ToListAsync());
        }

        public async Task<IActionResult> Busqueda()
        {
            return View();
        }



        public async Task<IActionResult> MostrarResultados(string parametro)
        {
                    return View("Index", await _context.Ventas.Where(v => v.CODGTE.Contains(parametro)).ToListAsync());
            // return View("Index", await _context.Ventas.Where(v => v.CODCOOR.Contains(parametro)).ToListAsync());
            // return View("Index", await _context.Ventas.Where(v => v.NOM_CLIENTE.Contains(parametro)).ToListAsync());
            // return View("Index", await _context.Ventas.Where(v => v.ITEM.Contains(parametro)).ToListAsync());


        }
        // GET: Ventas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ventas == null)
            {
                return NotFound();
            }


            var ventas = await _context.Ventas
                .FirstOrDefaultAsync(m => m.id == id);
            if (ventas == null)
            {
                return NotFound();
            }

            return View(ventas);
        }

        // GET: Ventas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,CODGTE,NOMGTE,CODCOOR,NOMCOOR,CODVENTAS,NOMVEND,CODNIVEL,NOMNIVEL,NIT_CLIENTE,ITEM,NOM_CLIENTE,SEGMENTO,GERENCIADO,OFICINA_CLIENTE,FECHAFIL,PERIODOMED,CONDIC,CTACAMP")] Ventas ventas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ventas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ventas);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ventas == null)
            {
                return NotFound();
            }

            var ventas = await _context.Ventas.FindAsync(id);
            if (ventas == null)
            {
                return NotFound();
            }
            return View(ventas);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,CODGTE,NOMGTE,CODCOOR,NOMCOOR,CODVENTAS,NOMVEND,CODNIVEL,NOMNIVEL,NIT_CLIENTE,ITEM,NOM_CLIENTE,SEGMENTO,GERENCIADO,OFICINA_CLIENTE,FECHAFIL,PERIODOMED,CONDIC,CTACAMP")] Ventas ventas)
        {
            if (id != ventas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ventas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VentasExists(ventas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ventas);
        }

        // GET: Ventas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ventas == null)
            {
                return NotFound();
            }

            var ventas = await _context.Ventas
                .FirstOrDefaultAsync(m => m.id == id);
            if (ventas == null)
            {
                return NotFound();
            }

            return View(ventas);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ventas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Ventas'  is null.");
            }
            var ventas = await _context.Ventas.FindAsync(id);
            if (ventas != null)
            {
                _context.Ventas.Remove(ventas);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VentasExists(int id)
        {
          return _context.Ventas.Any(e => e.id == id);
        }
    }
}

Prueba_Banco/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Prueba_Banco/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prueba_Banco</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prueba_Banco.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestión de compras</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Busqueda">Buscar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ventas" asp-action="Index">Ventas</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Prueba_Banco - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Prueba_Banco/Views/Ventas/Busqueda.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Buscar";
    }

<h1>Búsqueda</h1>

<hr />
<div>

     <form asp-action="Filtrar">

        <p>Seleccionar parámetro de búsqueda</p>
        <label for="criterio_busqueda"></label>
        <select name="criterio_busqueda" id="criterio_busqueda" size="1">
            <option value="CODGTE">CODGTE</option>
            <option value="CODCOOR">CODCOOR</option>
            <option value="NOM_CLIENTE">NOM_CLIENTE</option>
            <option value="ITEM">ITEM</option>
        </select>

    </form>


</divclass>



<div class="row">
    <div class="col-md-4">
        <form asp-action="MostrarResultados">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="parametro" class="control-label"></label>
                <input name="parametro" class="form-control" />
            </div>
            <br />
            <div class="form-group">
                    <input type="submit" value="Buscar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Prueba_Banco/Views/Ventas/Create.cshtml
@model Prueba_Banco.Models.Ventas

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Ventas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CODGTE" class="control-label"></label>
                <input asp-for="CODGTE" class="form-control" />
                <span asp-validation-for="CODGTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NOMGTE" class="control-label"></label>
                <input asp-for="NOMGTE" class="form-control" />
                <span asp-validation-for="NOMGTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CODCOOR" class="control-label"></label>
                <input asp-for="CODCOOR" class="form-control" />
                <span asp-validation-for="CODCOOR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NOMCOOR" class="control-label"></label>
                <input asp-for="NOMCOOR" class="form-control" />
                <span asp-validation-for="NOMCOOR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CODVENTAS" class="control-label"></label>
                <input asp-for="CODVENTAS" class="form-control" />
                <span asp-validation-for="CODVENTAS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NOMVEND" class="control-label"></label>
                <input asp-for="NOMVEND" class="form-control" />
                <span asp-validation-for="NOMVEND" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CODNIVEL" class="control-label"></label>
                <input asp-for="CODNIVEL" class="form-control" />
                <span asp-validation-for="CODNIVEL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NOMNIVEL" class="control-label"></label>
                <input asp-for="NOMNIVEL" class="form-control" />
                <span asp-validation-for="NOMNIVEL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NIT_CLIENTE" class="control-label"></label>
                <input asp-for="NIT_CLIENTE" class="form-control" />
                <span asp-validation-for="NIT_CLIENTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ITEM" class="control-label"></label>
                <input asp-for="ITEM" class="form-control" />
                <span asp-validation-for="ITEM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NOM_CLIENTE" class="control-label"></label>
                <input asp-for="NOM_CLIENTE" class="form-control" />
                <span asp-validation-for="NOM_CLIENTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SEGMENTO" class="control-label"></label>
                <input asp-for="SEGMENTO" class="form-control" />
                <span asp-validation-for="SEGMENTO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GERENCIADO" class="control-label"></label>
                <input asp-for="GERENCIADO" class="form-control" />
                <span asp-validation-for="GERENCIADO" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OFICINA_CLIENTE" class="control-label"></label>
                <input asp-for="OFICINA_CLIENTE" class="form-control" />
                <span asp-validation-for="OFICINA_CLIENTE" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FECHAFIL" class="control-label"></label>
                <input asp-for="FECHAFIL" class="form-control" />
                <span asp-validation-for="FECHAFIL" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PERIODOMED" class="control-label"></label>
                <input asp-for="PERIODOMED" class="form-control" />
                <span asp-validation-for="PERIODOMED" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CONDIC" class="control-label"></label>
                <input asp-for="CONDIC" class="form-control" />
                <span asp-validation-for="CONDIC" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CTACAMP" class="control-label"></label>
                <input asp-for="CTACAMP" class="form-control" />
                <span asp-validation-for="CTACAMP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Prueba_Banco/Views/Ventas/Delete.cshtml
@model Prueba_Banco.Models.Ventas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODGTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODGTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMGTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMGTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODCOOR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODCOOR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMCOOR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMCOOR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODVENTAS)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODVENTAS)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMVEND)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMVEND)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODNIVEL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODNIVEL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMNIVEL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMNIVEL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIT_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIT_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ITEM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ITEM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOM_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOM_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SEGMENTO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SEGMENTO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GERENCIADO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GERENCIADO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OFICINA_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OFICINA_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FECHAFIL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FECHAFIL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PERIODOMED)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PERIODOMED)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CONDIC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CONDIC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CTACAMP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CTACAMP)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Prueba_Banco/Views/Ventas/Details.cshtml
@model Prueba_Banco.Models.Ventas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ventas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODGTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODGTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMGTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMGTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODCOOR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODCOOR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMCOOR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMCOOR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODVENTAS)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODVENTAS)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMVEND)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMVEND)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CODNIVEL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CODNIVEL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOMNIVEL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOMNIVEL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NIT_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NIT_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ITEM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ITEM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NOM_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NOM_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SEGMENTO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SEGMENTO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GERENCIADO)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GERENCIADO)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OFICINA_CLIENTE)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OFICINA_CLIENTE)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FECHAFIL)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FECHAFIL)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PERIODOMED)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PERIODOMED)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CONDIC)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CONDIC)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CTACAMP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CTACAMP)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>